[package]
name = "s3foundation"
version = "0.1.0"
authors = ["Robert Beekman <robertbeekman@matsimitsu.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
foundationdb = "0.4"
futures = "0.3"
read-byte-slice = "*"
